---
- name: Configure Cisco Switch Port Based on Device Type and VLAN Lookup
  hosts: "{{ switch_name }}"
  gather_facts: no
  vars_files:
    - port_descriptions.yml  # Load port descriptions from file

  tasks:

    - name: Debugging - Show Retrieved Port Description
      debug:
        msg: "Port {{ port_number }} Description: {{ port_descriptions[port_number] | default('No description set') }}"

    - name: Set port description variable
      set_fact:
        port_description: "{{ port_descriptions[port_number] | default('No description set') }}"

    - name: Retrieve VLAN ID for device types `zero_client` & `phone`
      cisco.ios.ios_command:
        commands: "show vlan brief | include {{ device_type }}"
      register: vlan_output
      when: device_type in ['zero_client', 'phone']

    - name: Retrieve VLAN ID based on port number for `device` and `device and phone`
      cisco.ios.ios_command:
        commands: "show vlan brief | include Gi{{ port_number }}"
      register: port_vlan_output
      when: device_type in ['device', 'device and phone']

    - name: Debugging - Show Raw VLAN Output
      debug:
        msg: "{{ vlan_output.stdout | default('No output') }}"

    - name: Debugging - Show Raw VLAN Output for Ports
      debug:
        msg: "{{ port_vlan_output.stdout | default('No output') }}"
      when: device_type in ['device', 'device and phone']

    - name: Extract VLAN ID for `zero_client` & `phone`
      set_fact:
        vlan_id: >-
          {{
            vlan_output.stdout[0].split()[0]
            if vlan_output.stdout and vlan_output.stdout[0] | length > 0
            else '0'
          }}
      when: device_type in ['zero_client', 'phone']

    - name: Extract VLAN ID based on port assignment for `device` & `device and phone`
      set_fact:
        vlan_id: >-
          {{
            port_vlan_output.stdout[0].split()[0]
            if port_vlan_output.stdout and port_vlan_output.stdout[0] | length > 0
            else '0'
          }}
      when: device_type in ['device', 'device and phone']

    - name: Validate VLAN ID Before Applying Configuration
      fail:
        msg: "Error: VLAN ID could not be determined for {{ device_type }} on port {{ port_number }}. Check VLAN configuration on the switch."
      when: vlan_id in ['0']

    - name: Retrieve VLAN ID for phones
      cisco.ios.ios_command:
        commands: "show vlan brief | include phone"
      register: phone_vlan_output
      when: device_type in ['phone', 'device and phone']

    - name: Parse Phone VLAN ID from switch output
      set_fact:
        phone_vlan_id: "{{ phone_vlan_output.stdout[0].split()[0] if phone_vlan_output.stdout and phone_vlan_output.stdout[0] | length > 0 else '0' }}"
      when: device_type in ['phone', 'device and phone']

    - name: Debugging - Show VLAN IDs
      debug:
        msg:
          - "Device VLAN ID: {{ vlan_id }}"
          - "Phone VLAN ID: {{ phone_vlan_id | default('Not applicable') }}"

    - name: Reset the interface to default configuration
      cisco.ios.ios_config:
        lines:
          - "default interface GigabitEthernet{{ port_number }}"

    - name: Define configuration based on device type
      set_fact:
        config_lines: >-
          {{
            {
              'zero_client': [
                'description {{ port_description }}',
                'switchport mode access',
                'switchport access vlan {{ vlan_id }}',
                'duplex full',
                'switchport port-security mac-address sticky',
                'switchport port-security maximum 1',
                'switchport port-security',
                'no shutdown'
              ],
              'device': [
                'description {{ port_description }}',
                'switchport mode access',
                'switchport access vlan {{ vlan_id }}',
                'duplex full',
                'switchport port-security mac-address sticky',
                'switchport port-security maximum 1',
                'switchport port-security',
                'no shutdown'
              ],
              'phone': [
                'description {{ port_description }}',
                'switchport mode access',
                'switchport voice vlan {{ phone_vlan_id }}',
                'duplex full',
                'switchport port-security mac-address sticky',
                'switchport port-security maximum 1',
                'switchport port-security',
                'no shutdown'
              ],
              'device and phone': [
                'description {{ port_description }}',
                'switchport mode access',
                'switchport access vlan {{ vlan_id }}',
                'switchport voice vlan {{ phone_vlan_id }}',
                'duplex full',
                'switchport port-security mac-address sticky',
                'switchport port-security maximum 2',
                'switchport port-security',
                'no shutdown'
              ],
              'none': [
                'description {{ port_description }}',
                'shutdown'
              ]
            }[device_type]
          }}

    - name: Configure interface with VLAN, description, and security settings
      cisco.ios.ios_config:
        lines: "{{ config_lines }}"
        parents: "interface GigabitEthernet{{ port_number }}"

    - name: Debugging Output
      debug:
        msg:
          - "Applied Config: {{ config_lines }}"
