---
- name: Configure Cisco Switch Port Based on Device Type
  hosts: "{{ switch_name }}"
  gather_facts: no
  tasks:
    - name: Reset the interface to default configuration
      cisco.ios.ios_config:
        lines:
          - "default interface GigabitEthernet{{ port_number }}"

    - name: Define configuration based on device type
      set_fact:
        config_lines: >-
          {{
            {
              'zero client': [
                'switchport mode access',
                'switchport access vlan 541',
                'duplex full',
                'no shutdown'
              ],
              'zero client and phone': [
                'switchport mode access',
                'switchport access vlan 541',
                'switchport voice vlan 528',
                'duplex full',
                'no shutdown'
              ],
              'phone': [
                'switchport mode access',
                'switchport voice vlan 528',
                'duplex full',
                'no shutdown'
              ],
              'shutdown': [
                'shutdown'
              ]
            }[device_type]
          }}

    - name: Configure interface VLAN and State
      cisco.ios.ios_config:
        lines: "{{ config_lines }}"
        parents: "interface GigabitEthernet{{ port_number }}"

    - name: Debugging Output
      debug:
        msg:
          - "Applied Config: {{ config_lines }}"
